webtalk_init -webtalk_dir G:/S8/Nanosat/NANOSAT_11_04/CREME_DIGITAL/SPI/Test_SPI_n7/Test_SPI.sim/sim_1/behav/xsim/xsim.dir/ram_intel_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Mon Apr 11 16:55:32 2022" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2020.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "3064766" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "211907161_174131903_210695890_024" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "df6116cc-82aa-4362-94a0-f2b87eb19e62" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "3c61a2ac43e34e5e91b563c6fc1f8ff5" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "5" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-4590 CPU @ 3.30GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3292 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "2" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.03_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "6976_KB" -context "xsim\\usage"
webtalk_transmit -clientid 3044972381 -regid "211907161_174131903_210695890_024" -xml G:/S8/Nanosat/NANOSAT_11_04/CREME_DIGITAL/SPI/Test_SPI_n7/Test_SPI.sim/sim_1/behav/xsim/xsim.dir/ram_intel_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html G:/S8/Nanosat/NANOSAT_11_04/CREME_DIGITAL/SPI/Test_SPI_n7/Test_SPI.sim/sim_1/behav/xsim/xsim.dir/ram_intel_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm G:/S8/Nanosat/NANOSAT_11_04/CREME_DIGITAL/SPI/Test_SPI_n7/Test_SPI.sim/sim_1/behav/xsim/xsim.dir/ram_intel_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
