import sys
import traceback
from nxmap import *
#p = createProject()
#p.destroy()
p = createProject('/home/ggourves/Documents/NxMapProject/test_can_opencore')
p.setVariantName('NG-MEDIUM')
p.addFile('test_controleur_can.vhdl')
p.addFile('can_top.v')
p.addFile('can_registers.v')
p.addFile('can_register_syn.v')
p.addFile('can_register_asyn_syn.v')
p.addFile('can_register_asyn.v')
p.addFile('can_register.v')
p.addFile('can_ibo.v')
p.addFile('can_fifo.v')
p.addFile('can_defines.v')
p.addFile('can_crc.v')
p.addFile('can_btl.v')
p.addFile('can_bsp.v')
p.addFile('can_acf.v')
p.setTopCellName('test_controleur_can')
p.progress('Synthesize', 1)
p.destroy()
