webtalk_init -webtalk_dir D:/CREME_DIGITAL/I2C/test_I2C_1/test_I2C_1.sim/sim_1/behav/xsim/xsim.dir/tb_I2C_PERIPHERAL_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Mon Mar 28 16:18:03 2022" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2020.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "3064766" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "211907161_174131903_210695890_024" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "469e69c3-c9a4-4b08-90d6-751dff47c43c" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "24c58750813845b8ae3c582db6a5e685" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "15" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-4590 CPU @ 3.30GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3292 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1001 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "2" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.47_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "15372_KB" -context "xsim\\usage"
webtalk_transmit -clientid 3139782000 -regid "211907161_174131903_210695890_024" -xml D:/CREME_DIGITAL/I2C/test_I2C_1/test_I2C_1.sim/sim_1/behav/xsim/xsim.dir/tb_I2C_PERIPHERAL_behav/webtalk/usage_statistics_ext_xsim.xml -html D:/CREME_DIGITAL/I2C/test_I2C_1/test_I2C_1.sim/sim_1/behav/xsim/xsim.dir/tb_I2C_PERIPHERAL_behav/webtalk/usage_statistics_ext_xsim.html -wdm D:/CREME_DIGITAL/I2C/test_I2C_1/test_I2C_1.sim/sim_1/behav/xsim/xsim.dir/tb_I2C_PERIPHERAL_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
